# Generated by Django 3.1 on 2020-10-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
