# Generated by Django 3.1.2 on 2020-10-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_usercompleteprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
