# Generated by Django 3.1.2 on 2020-10-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20201030_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompleteprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
