# Generated by Django 3.1.2 on 2020-10-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20201031_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompleteprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pictures/'),
        ),
    ]
