# Generated by Django 3.1.2 on 2020-11-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20201104_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
