# Generated by Django 3.1.2 on 2020-12-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20201205_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompleteprofile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
