# Generated by Django 3.1.2 on 2020-12-08 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0021_usercompleteprofile_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('interest', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_name', models.CharField(max_length=40)),
                ('certificate_auth_id', models.CharField(max_length=60)),
                ('certificate_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
