# Generated by Django 3.1.2 on 2020-12-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20201211_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='expertise',
            field=models.CharField(choices=[('1', 'Low'), ('11', 'Normal'), ('111', 'High')], default='1', max_length=4),
        ),
    ]
