# Generated by Django 3.1.2 on 2020-12-29 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0027_auto_20201228_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_name', models.CharField(max_length=40)),
                ('certificate_auth_id', models.CharField(blank=True, max_length=60, null=True)),
                ('certificate_picture', models.ImageField(blank=True, null=True, upload_to='images/certificates/')),
                ('certificate_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='certificate_owner',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Certifications',
        ),
    ]
