# Generated by Django 3.2 on 2021-05-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20201229_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompleteprofile',
            name='phone_no',
        ),
    ]
